In [94]:
import math
from astropy.visualization import simple_norm
from multiprocessing import Value
import torch
from torch.utils.data import IterableDataset, DataLoader
import torchvision
import matplotlib.pyplot as plt
%matplotlib inline
from torchvision import transforms
import numpy as np
from skimage.segmentation import find_boundaries
import time
import h5py
import os
import pandas as pd
import ast


_GLOBAL_SEED = 0

class MaskCollator(object):

    def __init__(
        self,
        input_size=(224, 224),
        patch_size=16,
        enc_mask_scale=(0.2, 0.8),
        pred_mask_scale=(0.2, 0.8),
        aspect_ratio=(0.3, 3.0),
        nenc=1,
        npred=2,
        min_keep=4,
        allow_overlap=False
    ):
        super(MaskCollator, self).__init__()
        if not isinstance(input_size, tuple):
            input_size = (input_size, ) * 2
        self.patch_size = patch_size
        self.height, self.width = input_size[0] // patch_size, input_size[1] // patch_size
        self.enc_mask_scale = enc_mask_scale
        self.pred_mask_scale = pred_mask_scale
        self.aspect_ratio = aspect_ratio
        self.nenc = nenc
        self.npred = npred
        self.min_keep = min_keep  # minimum number of patches to keep
        self.allow_overlap = allow_overlap  # whether to allow overlap b/w enc and pred masks
        self._itr_counter = Value('i', -1)  # collator is shared across worker processes
        self.generator = torch.Generator()  # Initialize a generator
        self.generator.manual_seed(int(time.time()))  # Seed the generator once

    def step(self):
        i = self._itr_counter
        with i.get_lock():
            i.value += 1
            v = i.value
        return v

    def _sample_block_size(self, generator, scale, aspect_ratio_scale):
        _rand = torch.rand(1, generator=generator).item()
        # -- Sample block scale
        min_s, max_s = scale
        mask_scale = min_s + _rand * (max_s - min_s)
        max_keep = int(self.height * self.width * mask_scale)
        # -- Sample block aspect-ratio
        min_ar, max_ar = aspect_ratio_scale
        aspect_ratio = min_ar + _rand * (max_ar - min_ar)
        # -- Compute block height and width (given scale and aspect-ratio)
        h = int(round(math.sqrt(max_keep * aspect_ratio)))
        w = int(round(math.sqrt(max_keep / aspect_ratio)))
        while h >= self.height:
            h -= 1
        while w >= self.width:
            w -= 1

        return (h, w)

    def _sample_block_mask(self, b_size, acceptable_regions=None):
        h, w = b_size

        def constrain_mask(mask, tries=0):
            """ Helper to restrict given mask to a set of acceptable regions """
            N = max(int(len(acceptable_regions)-tries), 0)
            for k in range(N):
                mask *= acceptable_regions[k]
        # --
        # -- Loop to sample masks until we find a valid one
        tries = 0
        timeout = og_timeout = 20
        valid_mask = False
        while not valid_mask:
            # -- Sample block top-left corner
            top = torch.randint(0, self.height - h + 1, (1,))
            left = torch.randint(0, self.width - w + 1, (1,))
            max_top = self.height - h
            max_left = self.width - w
            mask = torch.zeros((self.height, self.width), dtype=torch.int32)
            mask[top:top+h, left:left+w] = 1
            # -- Constrain mask to a set of acceptable regions
            if acceptable_regions is not None:
                constrain_mask(mask, tries)
            mask = torch.nonzero(mask.flatten())
            # -- If mask too small try again
            valid_mask = len(mask) > self.min_keep
            if not valid_mask:
                timeout -= 1
                if timeout == 0:
                    tries += 1
                    timeout = og_timeout
                    print(f'Mask generator says: "Valid mask not found, decreasing acceptable-regions [{tries}]"')
        mask = mask.squeeze()
        # --
        mask_complement = torch.ones((self.height, self.width), dtype=torch.int32)
        mask_complement[top:top+h, left:left+w] = 0
        # --
        return mask, mask_complement

    def __call__(self, batch):
        '''
        Create encoder and predictor masks when collating imgs into a batch
        # 1. sample enc block (size + location) using seed
        # 2. sample pred block (size) using seed
        # 3. sample several enc block locations for each image (w/o seed)
        # 4. sample several pred block locations for each image (w/o seed)
        # 5. return enc mask and pred mask
        '''
        collated_batch = torch.utils.data.default_collate(batch)
        
        if len(collated_batch) == 2:
            collated_images = collated_batch[0]
            collated_metadata = collated_batch[1]
        else:
            collated_images = collated_batch
            collated_metadata = torch.zeros(len(collated_batch))
        B = len(batch)
        
        seed = self.step()
        g = torch.Generator()
        g.manual_seed(seed)
        p_size = self._sample_block_size(
            generator=g,
            scale=self.pred_mask_scale,
            aspect_ratio_scale=self.aspect_ratio)
        e_size = self._sample_block_size(
            generator=g,
            scale=self.enc_mask_scale,
            aspect_ratio_scale=(1., 1.))

        collated_masks_pred, collated_masks_enc = [], []
        min_keep_pred = self.height * self.width
        min_keep_enc = self.height * self.width
        for _ in range(B):

            masks_p, masks_C = [], []
            for _ in range(self.npred):
                mask, mask_C = self._sample_block_mask(p_size)
                masks_p.append(mask)
                masks_C.append(mask_C)
                min_keep_pred = min(min_keep_pred, len(mask))
            collated_masks_pred.append(masks_p)

            acceptable_regions = masks_C
            
            try:
                if self.allow_overlap:
                    acceptable_regions = None
            except Exception as e:
                print(f'Encountered exception in mask-generator {e}')

            masks_e = []
            for _ in range(self.nenc):
                mask, _ = self._sample_block_mask(e_size, acceptable_regions=acceptable_regions)
                masks_e.append(mask)
                min_keep_enc = min(min_keep_enc, len(mask))
            collated_masks_enc.append(masks_e)

        collated_masks_pred = [[cm[:min_keep_pred] for cm in cm_list] for cm_list in collated_masks_pred]
        collated_masks_pred = torch.utils.data.default_collate(collated_masks_pred)
        # --
        collated_masks_enc = [[cm[:min_keep_enc] for cm in cm_list] for cm_list in collated_masks_enc]
        collated_masks_enc = torch.utils.data.default_collate(collated_masks_enc)

        return collated_images, collated_metadata, collated_masks_enc, collated_masks_pred

def load_images(batch_size=4):
    # Transform to normalize the data
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor()
    ])
    
    # Load CIFAR10 images
    trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                            download=True, transform=transform)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                              shuffle=True, num_workers=2)
    # Fetch one batch of images
    dataiter = iter(trainloader)
    images, _ = next(dataiter)
    return list(images)

def upscale_mask(mask, patch_size):
    upscaled_mask = mask.repeat_interleave(patch_size, dim=0)
    upscaled_mask = upscaled_mask.repeat_interleave(patch_size, dim=1)
    return upscaled_mask

def visualize_masks(images, masks, masks_p, patch_size, alpha_grid, patch_grid=False):
    fig, axs = plt.subplots(nrows=len(images), ncols=3, figsize=(10, len(images) * 4))
    for i, (img, mask_indices, mask_indices_p) in enumerate(zip(images, masks, masks_p)):
        if images.shape[1] == 5:
            # only plot r-band
            img = img[2].detach().cpu().numpy()
            norm = simple_norm(img, 'sqrt', percent=98.)
            axs[i, 0].imshow(img, cmap='gray_r', norm=norm)
        else:
            img = img.permute(1, 2, 0).detach().cpu().numpy()  # Change CxHxW to HxWxC for plotting
            axs[i, 0].imshow(img)
        
        #axs[i, 0].set_xlim(0, img.shape[0])
        #axs[i, 0].set_ylim(0, img.shape[1])
        axs[i, 0].set_title('Original Image')
        axs[i, 0].axis('off')
        
        if patch_grid:
            for x in range(0, img.shape[0]+1, patch_size):
                axs[i, 0].axvline(x, color='black', linestyle='--', lw=0.2, alpha=alpha_grid)  # Adjust color and line style if needed
            for y in range(0, img.shape[1]+1, patch_size):
                axs[i, 0].axhline(y, color='black', linestyle='--', lw=0.2, alpha=alpha_grid)  # Adjust color and line style if needed
    
            for x in range(0, img.shape[0]+1, patch_size):
                axs[i, 1].axvline(x, color='black', linestyle='--', lw=0.2, alpha=alpha_grid)  # Adjust color and line style if needed
            for y in range(0, img.shape[1]+1, patch_size):
                axs[i, 1].axhline(y, color='black', linestyle='--', lw=0.2, alpha=alpha_grid)  # Adjust color and line style if needed

            for x in range(0, img.shape[0]+1, patch_size):
                axs[i, 2].axvline(x, color='black', linestyle='--', lw=0.2, alpha=alpha_grid)  # Adjust color and line style if needed
            for y in range(0, img.shape[1]+1, patch_size):
                axs[i, 2].axhline(y, color='black', linestyle='--', lw=0.2, alpha=alpha_grid)  # Adjust color and line style if needed
        
        full_mask = torch.zeros(mask_collator.height, mask_collator.width, dtype=torch.float32)
        for idx in mask_indices:
            row = idx // mask_collator.width
            col = idx % mask_collator.width
            full_mask[row, col] = 1
        
        part_masks_p = torch.zeros(mask_indices_p.shape[0], mask_collator.height, mask_collator.width, dtype=torch.float32)
        for j, part_mask in enumerate(mask_indices_p):
            for idx in part_mask:
                row = idx // mask_collator.width
                col = idx % mask_collator.width
                part_masks_p[j, row, col] = 1
        
        # Upscale mask to match image resolution
        full_mask = upscale_mask(full_mask, mask_collator.patch_size)

        part_masks_p = torch.stack([upscale_mask(sub_mask, mask_collator.patch_size) for sub_mask in part_masks_p])
        full_mask_p = torch.any(part_masks_p, dim=0)
        
        # Apply semi-transparent mask
        masked_img = img.copy()
        full_mask = full_mask.detach().cpu().numpy()
        alpha = 0.6  # transparency level
        # color_mask = np.ones_like(img) * [1, 0, 0]  # red mask
        # masked_img[full_mask == 0] = masked_img[full_mask == 0] * (1 - alpha) + color_mask[full_mask == 0] * alpha
        if images.shape[1] == 5:
            axs[i, 1].imshow(masked_img, cmap='gray_r', norm=norm)
        else:
            axs[i, 1].imshow(masked_img)
        axs[i, 1].imshow(np.ma.masked_where(full_mask == 1, full_mask), cmap='cool', vmin=-1, alpha=alpha)
        axs[i, 1].set_title('Final context mask')
        axs[i, 1].axis('off')

        masked_img_p = img.copy()
        # masked_img_p[full_mask_p == 0] = masked_img_p[full_mask_p == 0] * (1 - alpha) + color_mask[full_mask_p == 0] * alpha
        full_mask_p = full_mask_p.detach().cpu().numpy()
        if images.shape[1] == 5:
            axs[i, 2].imshow(masked_img_p, cmap='gray_r', norm=norm)
        else:
            axs[i, 2].imshow(masked_img_p)
        axs[i, 2].imshow(np.ma.masked_where(full_mask_p == 0, full_mask_p), cmap='cool', vmin=0, alpha=alpha, interpolation='none')
        all_mask_boundaries = np.zeros(full_mask_p.shape, dtype='bool')
        for k in range(part_masks_p.shape[0]):
            mask_boundaries = find_boundaries(part_masks_p[k].detach().cpu().numpy(), mode='thin')
            all_mask_boundaries |= mask_boundaries
        axs[i, 2].imshow(np.ma.masked_where(all_mask_boundaries==0, all_mask_boundaries), cmap='cool', vmin=1, alpha=alpha, interpolation='none')
        axs[i, 2].set_title('Target masks')
        axs[i, 2].axis('off')
    plt.show()
    return mask_boundaries

def read_h5(cutout_dir):
    """
    Reads cutout data from HDF5 file
    :param cutout_dir: cutout directory
    :return: cutout data
    """
    with h5py.File(cutout_dir, 'r') as f:
        # Create empty dictionaries to store data for each group
        cutout_data = {}

        # Loop through datasets
        for dataset_name in f:
            data = np.array(f[dataset_name])
            cutout_data[dataset_name] = data
    return cutout_data

class RealTileDataset(IterableDataset):
    def __init__(self, cutouts, metadata):
        """
        Initializes the dataset with real data.

        Args:
        cutouts (Tensor): A tensor or list of image data.
        metadata (Tensor): A tensor or list of corresponding metadata.
        """
        catalog = tensor_compatible(metadata)
        cutouts = torch.tensor(cutouts, dtype=torch.float32)
        catalog = torch.tensor(catalog.values, dtype=torch.float32)
        self.cutouts = cutouts
        self.metadata = catalog

    def __iter__(self):
        for cutout, meta in zip(self.cutouts, self.metadata):
            yield cutout, meta

    def __len__(self):
        # Return the total number of items in the dataset
        return len(self.cutouts)

def convert_to_binary(input_string):
    # Define the standard order of letters
    standard_letters = 'ugriz'
    # Initialize the result as an empty string
    result = ''
    # Iterate over each letter in the standard order
    for letter in standard_letters:
        # Append '2' if the letter is in the input string, '1' otherwise
        if letter in input_string:
            result += '2'
        else:
            result += '1'
    # Convert the binary string to a decimal integer
    return np.int32(result)


def split_tile_nums(df):
    # Split the tuple into two separate columns
    if isinstance(df['tile'][0], str):
        df['tile'] = df['tile'].apply(ast.literal_eval)
    df['tile_num1'], df['tile_num2'] = zip(*df['tile'])
    # Drop tile column
    df.drop('tile', axis=1, inplace=True)
    return df


def tensor_compatible(df):
    # Convert band info to integer number, 2 -> present, 1 -> absent
    if isinstance(df['bands'][0], str):
        df['bands'] = df['bands'].apply(convert_to_binary)
    if 'tile' in df.columns:
        # Split tile numbers up to two different columns and delete the tile column
        df = split_tile_nums(df)
    return df

### Hyper Parameters

In [95]:
input_size=(224, 224)
patch_size=8
enc_mask_scale=(0.85, 1.0)
pred_mask_scale=(0.02, 0.15)
aspect_ratio=(0.5, 1.5)
nenc=1
npred=6
min_keep=10
height, width = input_size[0] // patch_size, input_size[1] // patch_size
alpha_grid = 0.5

### Cutouts & Metadata

In [96]:
root = '/home/nick/astro/sky_embeddings/data'
cutouts = read_h5(os.path.join(root,'154_328_224x224_ugriz.h5'))
catalog = pd.read_csv(os.path.join(root,'(154, 328)_catalog.csv'))

### Initialize Dataset

In [97]:
mask_collator = MaskCollator(
input_size=input_size,
patch_size=patch_size,
pred_mask_scale=pred_mask_scale,
enc_mask_scale=enc_mask_scale,
aspect_ratio=aspect_ratio,
nenc=nenc,
npred=npred,
allow_overlap=False,
min_keep=min_keep)

dataset = RealTileDataset(cutouts=cutouts['images'], metadata=catalog)
#dist_sampler = torch.utils.data.distributed.DistributedSampler(dataset=dataset, num_replicas=1, rank=0)
dataloader = torch.utils.data.DataLoader(  # type: ignore
    dataset,
    batch_size=10,
    num_workers=0,
    pin_memory=True,
    drop_last=True,
    shuffle=False,
    collate_fn=mask_collator,
)

In [110]:
image_list = []
meta_list = []
mask_enc_list = []
mask_p_list = []

for images, meta, masks_enc, masks_p in dataloader:
    image_list.append(images)
    meta_list.append(meta)
    mask_enc_list.append(masks_enc)
    mask_p_list.append(masks_p)
    print(f'shapes: images {images.shape}, metadata: {meta.shape}, mask_enc: {torch.stack(masks_enc).shape}, masks_pred: {torch.stack(masks_p).shape}')

shapes: images torch.Size([10, 5, 224, 224]), metadata: torch.Size([10, 13]), mask_enc: torch.Size([1, 10, 315]), masks_pred: torch.Size([6, 10, 72])
shapes: images torch.Size([10, 5, 224, 224]), metadata: torch.Size([10, 13]), mask_enc: torch.Size([1, 10, 232]), masks_pred: torch.Size([6, 10, 117])
shapes: images torch.Size([10, 5, 224, 224]), metadata: torch.Size([10, 13]), mask_enc: torch.Size([1, 10, 314]), masks_pred: torch.Size([6, 10, 90])
shapes: images torch.Size([10, 5, 224, 224]), metadata: torch.Size([10, 13]), mask_enc: torch.Size([1, 10, 276]), masks_pred: torch.Size([6, 10, 99])
shapes: images torch.Size([10, 5, 224, 224]), metadata: torch.Size([10, 13]), mask_enc: torch.Size([1, 10, 351]), masks_pred: torch.Size([6, 10, 72])
shapes: images torch.Size([10, 5, 224, 224]), metadata: torch.Size([10, 13]), mask_enc: torch.Size([1, 10, 268]), masks_pred: torch.Size([6, 10, 108])
shapes: images torch.Size([10, 5, 224, 224]), metadata: torch.Size([10, 13]), mask_enc: torch.Size

In [114]:
images.squeeze(1).shape, masks_p[0].shape

(torch.Size([10, 5, 224, 224]), torch.Size([10, 72]))

In [81]:
images_in = load_images(batch_size=4)

mask_collator = MaskCollator(
input_size=input_size,
patch_size=patch_size,
pred_mask_scale=pred_mask_scale,
enc_mask_scale=enc_mask_scale,
aspect_ratio=aspect_ratio,
nenc=nenc,
npred=npred,
allow_overlap=False,
min_keep=min_keep)

Files already downloaded and verified


In [82]:
images, meta, masks_enc, masks_p = mask_collator(images_in)
print(f'shapes: images: {images.shape}, meta: {meta.shape}, masks_enc: {masks_enc[0].shape}, masks_p: {torch.stack(masks_p).shape}')
idx = 2
#images, meta, masks_enc, masks_p = image_list[idx], meta_list[idx], mask_enc_list[idx], mask_p_list[idx]
stacked_masks_p = torch.stack(masks_p)
reshaped_masks = torch.unbind(stacked_masks_p, dim=1)
# Just use one set of encoder masks for demonstration
mask_indices_p = full_mask_p = visualize_masks(images, masks_enc[0], reshaped_masks, patch_size, alpha_grid, patch_grid=False)

RuntimeError: stack expects each tensor to be equal size, but got [420] at entry 0 and [433] at entry 1

In [87]:
masks_enc[0].shape

torch.Size([4, 293])

In [91]:
masks_p[0].shape

torch.Size([4, 99])

In [75]:
masks_p

[tensor([[146, 147, 148, 149, 150, 151, 152, 153, 154, 174, 175, 176, 177, 178,
          179, 180, 181, 182, 202, 203, 204, 205, 206, 207, 208, 209, 210, 230,
          231, 232, 233, 234, 235, 236, 237, 238, 258, 259, 260, 261, 262, 263,
          264, 265, 266, 286, 287, 288, 289, 290, 291, 292, 293, 294, 314, 315,
          316, 317, 318, 319, 320, 321, 322, 342, 343, 344, 345, 346, 347, 348,
          349, 350, 370, 371, 372, 373, 374, 375, 376, 377, 378, 398, 399, 400,
          401, 402, 403, 404, 405, 406, 426, 427, 428, 429, 430, 431, 432, 433,
          434],
         [311, 312, 313, 314, 315, 316, 317, 318, 319, 339, 340, 341, 342, 343,
          344, 345, 346, 347, 367, 368, 369, 370, 371, 372, 373, 374, 375, 395,
          396, 397, 398, 399, 400, 401, 402, 403, 423, 424, 425, 426, 427, 428,
          429, 430, 431, 451, 452, 453, 454, 455, 456, 457, 458, 459, 479, 480,
          481, 482, 483, 484, 485, 486, 487, 507, 508, 509, 510, 511, 512, 513,
          514, 515, 535,

In [73]:
masks_p[0].shape

torch.Size([4, 99])

In [233]:
meta[0][3:5]

tensor([279.7404,  73.7502])

In [295]:
meta[2][3:5], meta[3][3:5], meta[4][3:5]

(tensor([279.6951,  73.7498]),
 tensor([278.9959,  73.7484]),
 tensor([278.8341,  73.7476]))

In [222]:
root = '/home/nick/astro/sky_embeddings'
tile_cat = pd.read_csv(os.path.join(root, '(150, 322)_catalog.csv'))

In [224]:
tile_cat_test = tile_cat[:10].reset_index(drop=True)
tile_cat_test = tensor_compatible(tile_cat_test)
for row in tile_cat_test.itertuples(index=False):
    print(row)

Pandas(ID=1, x=7216.109, y=202.7967, ra=230.0196166, dec=70.7521278, mag_r=14.492716, bands=22222, _7=1.0, zspec=-9.359808609588072e-05, lens=nan, lsb=nan, tile_num1=150, tile_num2=322)
Pandas(ID=2, x=7859.331, y=145.4179, ra=229.9190009, dec=70.7489498, mag_r=14.93888, bands=22222, _7=1.0, zspec=-0.0002071432973025, lens=nan, lsb=nan, tile_num1=150, tile_num2=322)
Pandas(ID=3, x=2550.8567, y=149.6538, ra=230.7498303, dec=70.7493132, mag_r=18.307415, bands=22222, _7=2.0, zspec=0.2250169962644577, lens=nan, lsb=nan, tile_num1=150, tile_num2=322)
Pandas(ID=4, x=5071.8354, y=138.8921, ra=230.3552686, dec=70.7491567, mag_r=15.6933365, bands=22222, _7=nan, zspec=nan, lens=nan, lsb=nan, tile_num1=150, tile_num2=322)
Pandas(ID=5, x=7765.232, y=132.1593, ra=229.9337425, dec=70.7483008, mag_r=18.250532, bands=22222, _7=2.0, zspec=0.0768089964985847, lens=nan, lsb=nan, tile_num1=150, tile_num2=322)
Pandas(ID=6, x=3870.8833, y=101.8959, ra=230.5432114, dec=70.7471632, mag_r=17.612999, bands=22222

In [233]:
torch_row = torch.tensor(tile_cat_test.values, dtype=torch.float32)

In [236]:
torch_row[0]

tensor([ 1.0000e+00,  7.2161e+03,  2.0280e+02,  2.3002e+02,  7.0752e+01,
         1.4493e+01,  2.2222e+04,  1.0000e+00, -9.3598e-05,         nan,
                nan,  1.5000e+02,  3.2200e+02])

In [212]:
def convert_to_binary(input_string):
    # Define the standard order of letters
    standard_letters = 'ugriz'
    # Initialize the result as an empty string
    result = ''
    # Iterate over each letter in the standard order
    for letter in standard_letters:
        # Append '2' if the letter is in the input string, '1' otherwise
        if letter in input_string:
            result += '2'
        else:
            result += '1'
    # Convert the binary string to a decimal integer
    return np.int32(result)

def split_tile_nums(df):
    # Split the tuple into two separate columns
    if type(df['tile'][0]) != tuple:
        df['tile'] = df['tile'].apply(ast.literal_eval)
    df['tile_num1'], df['tile_num2'] = zip(*df['tile'])
    # Drop tile column
    df.drop('tile', axis=1, inplace=True)
    return df

def tensor_compatible(df):
    # Convert band info to integer number, 2 -> present, 1 -> absent
    if type(df['bands'][0]) == str:
        df['bands'] = df['bands'].apply(convert_to_binary)
    # Split tile numbers up to two different columns and delete the tile column
    df = split_tile_nums(df)
    return df

In [213]:
tensor_compatible(df)

ID          x         y          ra        dec      mag_r  bands  class  \
0   1  7216.1090  202.7967  230.019617  70.752128  14.492716  22222    1.0   
1   2  7859.3310  145.4179  229.919001  70.748950  14.938880  22222    1.0   
2   3  2550.8567  149.6538  230.749830  70.749313  18.307415  22222    2.0   
3   4  5071.8354  138.8921  230.355269  70.749157  15.693336  22222    NaN   
4   5  7765.2320  132.1593  229.933742  70.748301  18.250532  22222    2.0   
5   6  3870.8833  101.8959  230.543211  70.747163  17.612999  22222    2.0   
6   7  5708.7350   99.6722  230.255599  70.747100  15.712096  22222    NaN   
7   8  6033.1694   79.4746  230.204836  70.746020  16.130112  22222    NaN   
8   9  6007.2246   72.6927  230.208899  70.745674  17.306929  22222    NaN   
9  10  9329.2500   61.6149  229.689110  70.743923  16.817242  22222    NaN   

      zspec  lens  lsb  tile_num1  tile_num2  
0 -0.000094   NaN  NaN        150        322  
1 -0.000207   NaN  NaN        150        322  
2  0.225017   NaN  NaN        150        322  
3       NaN   NaN  NaN        150        322  
4  0.076809   NaN  NaN        150        322  
5  0.183967   NaN  NaN        150        322  
6       NaN   NaN  NaN        150        322  
7       NaN   NaN  NaN        150        322  
8       NaN   NaN  NaN        150        322  
9       NaN   NaN  NaN        150        322

In [120]:
test = '[(123,456),(111,222)]'
test_eval = ast.literal_eval(test)

In [122]:
test_eval

[(123, 456), (111, 222)]